$("button").on("click",function(){
   var description= $(this).siblings().last().val()
   var time = $(this).siblings().first().text()
   console.log(time)
   console.log (description)
   localStorage.setItem(time,description)
})

console.log(localStorage.getItem("9am"))
$(".time:contains('9am')").siblings().first().val(localStorage.getItem("9am"))
$(".time:contains('10am')").siblings().first().val(localStorage.getItem("10am"))
$(".time:contains('11am')").siblings().first().val(localStorage.getItem("11am"))
$(".time:contains('12pm')").siblings().first().val(localStorage.getItem("12pm"))
$(".time:contains('1pm')").siblings().first().val(localStorage.getItem("1pm"))
$(".time:contains('2pm')").siblings().first().val(localStorage.getItem("2pm"))
$(".time:contains('3pm')").siblings().first().val(localStorage.getItem("3pm"))
$(".time:contains('4pm')").siblings().first().val(localStorage.getItem("4pm"))
$(".time:contains('5pm')").siblings().first().val(localStorage.getItem("5pm"))
$("#currentDay").text(moment().format("YYYY-MM-DD"))
